all: au197_548_histos.root
	echo "Geant4 simulations done."

# Pattern rules for running Geant4 simulations and sorting the output
# into Root histograms
%.log : %.mac
	UCGretina $*.mac > $*.log
	rm $*.out

%.dat : %.mac
	UCGretina $*.mac | tee $*.log

%_sim.root : %.dat
	SimCalculate -i $*.dat -o $*_sim.root -s s44.set | tee $*_sim.log

%_histos.root : %_sim.root
	Sim_histos -i $*_sim.root -o $*_histos.root | tee $*_histos.log

clean:
	rm *.log *.dat *.root

