# Detector parameters ==========================================================
/Gretina/detector/enableCapsules
/Gretina/detector/enableCryostats
/Gretina/Shell north
/Target/Cell thick
/Target/Bulge 1.0 mm
/Target/Angle 30. deg
/Target/Construct

# Multithreading settings (ignored without multithreading support) =============
/run/numberOfThreads 16 # must be <= available threads provided by the CPU 
/run/eventModulo 6250   # ensures a (necessary) even distribution of events
                        # among threads and therefore among cache files

# Initialize run manager =======================================================
/run/initialize

/Cache/Input s44_1329.cache
/Cache/GammaEnergy 1329 keV
/Cache/HalfLife 2.4 ps

# Print simulation parameters to stdout ========================================
/Target/Report
/ExpHall/Report

# Tracking parameters ==========================================================
#/GammaPrint/Track_Set
#/IonPrint/Track_Set

# Output parameters ============================================================
#/Mode2/PackingRes 0.0 mm
/Mode2/crmatFile crmat.LINUX
/Mode2/GretinaCoords
/Mode2/S800KE 3.353 GeV
#/Mode2/Print
/Mode2/Filename s44_1329.dat

/run/beamOn 100000
