# Detector parameters ==========================================================
/Gretina/detector/enableCapsules
/Gretina/detector/enableCryostats
/Gretina/Shell north
/Target/Cell thick
/Target/Bulge 1.0 mm
/Target/Angle 30. deg
/Target/Construct

# Multithreading settings (ignored without multithreading support) =============
/run/numberOfThreads 16 # must be <= available threads provided by the CPU 
/run/eventModulo 6250   # ensures a (necessary) even distribution of events
                        # among threads and therefore among cache files

# Initialize run manager =======================================================
/run/initialize

# Set reaction parameters ======================================================
/BeamIn/A 44
/BeamIn/Z 16
/BeamIn/KEu 100.0 MeV
/BeamIn/Dpp 0.02
/BeamIn/Focus/DX 4. mm
/BeamIn/Focus/DY 8. mm

/BeamOut/TargetA 1
/BeamOut/TargetZ 1
/BeamOut/DA 0
/BeamOut/DZ 0
/BeamOut/LevelDataFile z16.a44.lvldata
/BeamOut/ProjectileExcitation 1329 keV
/BeamOut/AngDistSigmaA 0.006 rad
/BeamOut/AngDistSigmaB 0.006 rad
/BeamOut/Update

# Print simulation parameters to stdout ========================================
/Target/Report
/ExpHall/Report

# Tracking parameters ==========================================================
#/GammaPrint/Track_Set
#/IonPrint/Track_Set

# Output parameters ============================================================
#/Mode2/PackingRes 0.0 mm
/Mode2/crmatFile crmat.LINUX
/Mode2/GretinaCoords
/Mode2/S800KE 3.353 GeV
#/Mode2/Print
#/Mode2/Filename s44_1329.dat
/Cache/Output s44_1329.cache
/run/beamOn 100000

